version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    env_file: .env
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      - MYSQL_DATABASE=realty
    volumes:
      - ./.srv/database:/var/lib/mysql

  # redis:
  #   image: redis:alpine
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   environment:
  #     - REDIS_DATABASES=1
  #   command:
  #     [
  #       "redis-server",
  #       "--maxmemory",
  #       "1024mb",
  #       "--maxmemory-policy",
  #       "allkeys-lru",
  #     ]

  wordpress:
    depends_on:
      - db
      # - redis
    image: wordpress:php8.1-fpm
    container_name: wordpress
    restart: always
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=realty
      - WORDPRESS_DEBUG=0
      # - WORDPRESS_CACHE=true
      # - WORDPRESS_REDIS_HOST=redis
    volumes:
      - "./.srv/realty:/var/www/html"
      - "./assets/:/var/www/html/assets"
      - "./config/get_json.php:/var/www/html/get_json.php"
      - "./config/custom.ini:/usr/local/etc/php/conf.d/custom.ini"
      - "./config/critical_error_message_telegram.php:/var/www/html/critical_error_message_telegram.php"
      - "./config/my_cron_file:/etc/cron.d/my_cron_file"
      - "./config/cron.log:/var/log/cron.log"
      - "./config/entrypoint.sh:/usr/local/bin/entrypoint.sh"
      - "./map/:/var/www/html/map"
      - "./mlsfiles/:/var/www/html/wp-content/mlsfiles"
      - "./theme/:/var/www/html/wp-content/themes/realty"
      - "./uploads/:/var/www/html/wp-content/uploads"
      - "./plugins/:/var/www/html/wp-content/plugins"
    entrypoint: ["/bin/bash", "/usr/local/bin/entrypoint.sh"]
    command: >
      bash -c "apt-get update && apt-get install -y cron &&
      chmod 0644 /etc/cron.d/my_cron_file &&
      crontab /etc/cron.d/my_cron_file &&
      cron && php-fpm"

  webserver:
    depends_on:
      - wordpress
    image: nginx:latest
    container_name: webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - "./.srv/realty:/var/www/html"
      - "./assets/:/var/www/html/assets"
      - "./map/:/var/www/html/map"
      - "./mlsfiles/:/var/www/html/wp-content/mlsfiles"
      - "./uploads/:/var/www/html/wp-content/uploads"
      - "./theme/:/var/www/html/wp-content/themes/realty"
      - "./plugins/:/var/www/html/wp-content/plugins"
      - certbot-etc:/etc/letsencrypt

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_USERNAME: Andrei
      PMA_HOST: db
      UPLOAD_LIMIT: 1512M

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - "./.srv/realty:/var/www/html"
      - "./assets/:/var/www/html/assets"
      - "./config/custom.ini:/usr/local/etc/php/conf.d/custom.ini"
      - "./theme/:/var/www/html/wp-content/themes/realty"
    command: certonly --webroot --webroot-path=/var/www/html --email andreikrautsougit@yandex.ru --agree-tos --no-eff-email --force-renewal -d obj-estate.ru -d www.obj-estate.ru

volumes:
  certbot-etc:
